baseurl = "http://painter-rabbit-30841.netlify.com/"
copyright = "My Name"
disqusShortname = "XXX"
googleAnalytics = "XXX"
languageCode = "en-us"
theme = "ghostwriter"
title = "Ghostwriter example"
[Author]
name = "My Name"
profile = "https://google.com/+XXX"
[Permalinks]
post = "/:year/:month/:day/:filename/"
[Taxonomies]
tag = "tags"
[[menu.main]]
name = "About"
url = "/page/about/"
weight = 4
[[menu.main]]
name = "Contact"
url = "/page/contact/"
weight = 3
[[menu.main]]
name = "Projects"
url = "/project/"
weight = 2
[[menu.main]]
name = "Blog"
url = "/"
weight = 1
[params]
dateformat = "Mon, Jan 2, 2006"
description = "Ghostwriter example description"
email = "XXX@example.com"
github = "https://github.com/XXX"
gitlab = "https://gitlab.com/XXX"
gplus = "https://google.com/+XXX"
headline = "Ghostwriter example"
intro = true
linkedin = "https://linkedin.com/in/XXX/"
opengraph = true
sharefacebook = true
sharegoogleplus = true
sharelinkedin = false
sharetwitter = true
stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
twitter = "https://twitter.com/XXX"
